---
- name: gather the package facts
  package_facts:
    manager: auto
- name: abort if systemd is not installed
  fail:
    msg: "systemd is not installed on this machine"
  when: '"systemd" not in ansible_facts.packages'
